---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/docker-cpi

run:
  path: /bin/bash
  args:
    - -exc
    - |
      echo "No new tarball was detected. Skipping upload to blobstore and commit so we avoid blobstore checksum mismatches."
