---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/docker-cpi

run:
  path: /bin/bash
  args:
    - -exc
    - |
      echo "No new asset was detected. Skipping commit so we avoid checksum mismatches."
